version: '3.4'

services:
  isfg.emailbox:
    image: spisum-emailbox
    build:
      context: .
      dockerfile: ISFG.EmailBox/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:7778
      - ASPNETCORE_LOG=Logs/log.txt
    ports:
      - "7778:7778"
